/*
 * Copyright (c) [2020], MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws.
 * The information contained herein is confidential and proprietary to
 * MediaTek Inc. and/or its licensors.
 * Except as otherwise provided in the applicable licensing terms with
 * MediaTek Inc. and/or its licensors, any reproduction, modification, use or
 * disclosure of MediaTek Software, and information contained herein, in whole
 * or in part, shall be strictly prohibited.
*/

#ifndef __MTK_NL80211_H_
#define __MTK_NL80211_H_

#include "iwinfo.h"
#include <linux/types.h>

/* ---------- MediaTek vendor extension (from mtk_vendor_nl80211.h) ---------- */
#define MTK_NL80211_VENDOR_ID			0x0ce7

/* mtk_nl80211_vendor_commands: GET_STA: 0xea */
//#define MTK_NL80211_VENDOR_SUBCMD_GET_STA	0x000000ea
//#define MTK_NL80211_VENDOR_SUBCMD_GET_CONNECTED_STA_MLD		0x00000102

enum mtk_nl80211_vendor_commands {
	MTK_NL80211_VENDOR_SUBCMD_UNSPEC = 0,
	MTK_NL80211_VENDOR_SUBCMD_TEST = 1,

/* don't change the order or add anything between, this is ABI! */
	MTK_NL80211_VENDOR_SUBCMD_AMNT_CTRL = 0x000000ae,
	MTK_NL80211_VENDOR_SUBCMD_CSI_CTRL = 0x000000c2,
	MTK_NL80211_VENDOR_SUBCMD_AP_RFEATURE,
	MTK_NL80211_VENDOR_SUBCMD_AP_WIRELESS,
	MTK_NL80211_VENDOR_SUBCMD_SET_DOT11V_WNM,
	MTK_NL80211_VENDOR_SUBCMD_GET_CAP,
	MTK_NL80211_VENDOR_SUBCMD_GET_RUNTIME_INFO,
	MTK_NL80211_VENDOR_SUBCMD_GET_STATISTIC,
	MTK_NL80211_VENDOR_SUBCMD_GET_STATIC_INFO,
	MTK_NL80211_VENDOR_SUBCMD_MAC,
	MTK_NL80211_VENDOR_SUBCMD_STATISTICS,
	MTK_NL80211_VENDOR_SUBCMD_VENDOR_SET,
	MTK_NL80211_VENDOR_SUBCMD_VENDOR_SHOW,
	MTK_NL80211_VENDOR_SUBCMD_WAPP_REQ,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_SECURITY,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_VOW,
	MTK_NL80211_VENDOR_SUBCMD_SET_MWDS,
	MTK_NL80211_VENDOR_SUBCMD_SET_COUNTRY,
	MTK_NL80211_VENDOR_SUBCMD_SET_CHANNEL,
	MTK_NL80211_VENDOR_SUBCMD_SET_AUTO_CH_SEL,
	MTK_NL80211_VENDOR_SUBCMD_SET_SCAN,
	MTK_NL80211_VENDOR_SUBCMD_SET_ACL,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_BSS,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_RADIO,
	MTK_NL80211_VENDOR_SUBCMD_SET_WMM,
	MTK_NL80211_VENDOR_SUBCMD_SET_FT,
	MTK_NL80211_VENDOR_SUBCMD_SET_ACTION,
	MTK_NL80211_VENDOR_SUBCMD_QOS,
	MTK_NL80211_VENDOR_SUBCMD_OFFCHANNEL_INFO,
	MTK_NL80211_VENDOR_SUBCMD_DFS,
	MTK_NL80211_VENDOR_SUBCMD_EASYMESH,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_MONITOR,
	MTK_NL80211_VENDOR_SUBCMD_SET_VLAN,
	MTK_NL80211_VENDOR_SUBCMD_SET_BA,
	MTK_NL80211_VENDOR_SUBCMD_SET_MLO_PRESET_LINK,
	MTK_NL80211_VENDOR_SUBCMD_SET_TXPOWER,
	MTK_NL80211_VENDOR_SUBCMD_SET_EDCA,
	MTK_NL80211_VENDOR_SUBCMD_SET_MULTICAST_SNOOPING,
	MTK_NL80211_VENDOR_SUBCMD_GET_RADIO_STATS,
	MTK_NL80211_VENDOR_SUBCMD_SET_RADIO_STATS,
	MTK_NL80211_VENDOR_SUBCMD_GET_BSS_STATS,
	MTK_NL80211_VENDOR_SUBCMD_GET_STA,
	MTK_NL80211_VENDOR_SUBCMD_SET_MBO,
	MTK_NL80211_VENDOR_SUBCMD_HQA,
	MTK_NL80211_VENDOR_SUBCMD_SET_ATE,
	MTK_NL80211_VENDOR_SUBCMD_SET_MLO_IE,
	MTK_NL80211_VENDOR_SUBCMD_SET_PMKID,
	MTK_NL80211_VENDOR_SUBCMD_SET_V10CONVERTER,
	MTK_NL80211_VENDOR_SUBCMD_SET_APPROXYREFRESH,
	MTK_NL80211_VENDOR_SUBCMD_E2P,
	MTK_NL80211_VENDOR_SUBCMD_TESTENGINE,
	MTK_NL80211_VENDOR_SUBCMD_SET_COSR_IE,
	MTK_NL80211_VENDOR_SUBCMD_SET_COSR_INFO,
	MTK_NL80211_VENDOR_SUBCMD_GET_APCLI_MLD,
	MTK_NL80211_VENDOR_SUBCMD_SHOW_MLO_INFO = MTK_NL80211_VENDOR_SUBCMD_GET_APCLI_MLD,
	MTK_NL80211_VENDOR_SUBCMD_SET_MLO_SWITCH,
	MTK_NL80211_VENDOR_SUBCMD_GET_AP_MLD,
	MTK_NL80211_VENDOR_SUBCMD_GET_BSS_MLO_INFO = MTK_NL80211_VENDOR_SUBCMD_GET_AP_MLD,
	MTK_NL80211_VENDOR_SUBCMD_SET_MAC,
	MTK_NL80211_VENDOR_SUBCMD_SEQ_NUM,
	MTK_NL80211_VENDOR_SUBCMD_OFFLOAD_ACS,
	MTK_NL80211_VENDOR_SUBCMD_BH_STATUS,
	MTK_NL80211_VENDOR_SUBCMD_GET_BAND_INFO,
	MTK_NL80211_VENDOR_SUBCMD_DEL_MLO_STA_ENTRY,
	MTK_NL80211_VENDOR_SUBCMD_FTM,
	MTK_NL80211_VENDOR_SUBCMD_FTM_STAT,
	MTK_NL80211_VENDOR_SUBCMD_CONFIG,
	MTK_NL80211_VENDOR_SUBCMD_GET_CONNECTED_STA_MLD,
	MTK_NL80211_VENDOR_SUBCMD_GET_AP_BSS,
	MTK_NL80211_VENDOR_SUBCMD_CLEAN_STATION,
	MTK_NL80211_VENDOR_SUBCMD_SET_SWACI_LNA,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_MLD,
	MTK_NL80211_VENDOR_SUBCMD_SET_NPCA,
	MTK_NL80211_VENDOR_SUBCMD_SET_DSO,
	MTK_NL80211_VENDOR_SUBCMD_SET_CBF,
	MTK_NL80211_VENDOR_SUBCMD_SET_CSR,
	MTK_NL80211_VENDOR_SUBCMD_SET_MLO_KDE,
	MTK_NL80211_VENDOR_SUBCMD_SET_ZR_HDO_RM,
	MTK_NL80211_VENDOR_SUBCMD_GET_ZR_HDO_RM,
	MTK_NL80211_VENDOR_SUBCMD_SET_AP_PTK,
	MTK_NL80211_VENDOR_SUBCMD_SET_PASN_KEY,
	MTK_NL80211_VENDOR_SUBCMD_SET_SPECTRUM,
	MTK_NL80211_VENDOR_SUBCMD_GET_SPECTRUM,
	/* add new commands above here */
	/* used to define NL80211_CMD_MAX below */
	__MTK_NL80211_VENDOR_CMD_AFTER_LAST,
	MTK_NL80211_VENDOR_CMD_MAX = __MTK_NL80211_VENDOR_CMD_AFTER_LAST - 1
};

enum mtk_nl80211_vendor_attrs_sta {
/* don't change the order or add anything between, this is ABI! */
	MTK_NL80211_VENDOR_ATTR_STA_INVALID = 0,
	MTK_NL80211_VENDOR_ATTR_STA,
	/* add attributes here, update the policy in nl80211.c */
	MTK_NL80211_VENDOR_ATTR_STA_MAC,
	MTK_NL80211_VENDOR_ATTR_STA_INFO,
	MTK_NL80211_VENDOR_ATTR_STA_INFO_GTBAPP_FORMAT,
	MTK_NL80211_VENDOR_ATTR_STA_INFO_ANDLINK_FORMAT,
	MTK_NL80211_VENDOR_ATTR_STA_BAND_LINK_ID,

	__MTK_NL80211_VENDOR_ATTR_STA_LAST,
	MTK_NL80211_VENDOR_ATTR_STA_ATTR_MAX = __MTK_NL80211_VENDOR_ATTR_STA_LAST - 1
};

/*
 * copy mtk_vendor_nl80211.h:  mtk_nl80211_vendor_attrs_sta_mld.
 */
enum mtk_nl80211_vendor_attrs_sta_mld {
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_INVALID = 0,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_INDEX_TO_DUMP,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_MAC,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_EMLMR,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_EMLSR,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_STR,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_NSTR,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_LAST_CONNECT_TIME,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_MAC,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_BSSID,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_LINKID,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_TID_MAP_UL,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_TID_MAP_DL,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_BYTES_SENT,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_BYTES_RECEIVED,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_PACKETS_SENT,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_PACKETS_RECEIVED,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_ERRORS_SENT,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_RETRIES,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_SIGNAL_STRENGTH,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_SNR,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_EST_DL_RATE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_EST_UL_RATE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_LAST_DL_RATE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_LAST_UL_RATE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_AIR_TIME_RECEIVE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_AIR_TIME_TRANSMIT,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_PHY_MODE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_PHY_MODE,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_BW,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_BW,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_MCS,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_MCS,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_NSS,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_NSS,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_SGI,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_SGI,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_UL_DCM,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_AFFILIATED_STA_DL_DCM,
	__MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_LAST,
	MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_MAX =
		__MTK_NL80211_VENDOR_ATTR_CONNECTED_STA_MLD_LAST - 1
};

enum mtk_nl80211_vendor_attrs_ap_mld {
/* don't change the order or add anything between, this is ABI! */
	MTK_NL80211_VENDOR_ATTR_AP_MLD_INVALID = 0,
	MTK_NL80211_VENDOR_ATTR_BSS_MLO_INFO,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_INDEX,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_ADDRESS,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_DUMP,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_AFFILIATED_APS,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_AFFILIATED_AP_BSSID,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_AFFILIATED_AP_LINKID,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_AFFILIATED_AP_RUID,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_AFFILIATED_AP_DISABLED_SUBCHAN,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_EMLMR,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_EMLSR,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_STR,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_NSTR,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_CONNECTED_STA_MLDS_DUMP,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_TYPE,

	/* add attributes here, update the policy in nl80211.c */

	__MTK_NL80211_VENDOR_ATTR_AP_MLD_LAST,
	MTK_NL80211_VENDOR_ATTR_AP_MLD_ATTR_MAX = __MTK_NL80211_VENDOR_ATTR_AP_MLD_LAST - 1,
	MTK_NL80211_VENDOR_ATTR_BSS_MLO_INFO_ATTR_MAX = MTK_NL80211_VENDOR_ATTR_AP_MLD_ATTR_MAX
};

struct mtk_mlo_link_information {
	unsigned char valid;
	unsigned char link_address[6];
	unsigned long long rx_bytes;
	unsigned long long tx_bytes;
	unsigned long rx_packets;
	unsigned long tx_packets;
	signed char rssi[4];
	unsigned char snr[4];
	unsigned long tx_rate;
	unsigned long rx_rate;
};

struct mtk_station_information {
	unsigned char mac[6];
	unsigned char tx_phymode;
	unsigned char rx_phymode;
	unsigned char tx_bw;
	unsigned char rx_bw;
	unsigned char tx_nss;
	unsigned char tx_mcs;
	unsigned char rx_nss;
	unsigned char rx_mcs;
	unsigned long long rx_bytes;
	unsigned long long tx_bytes;
	unsigned long rx_packets;
	unsigned long tx_packets;
	signed char rssi[4];
	unsigned char snr[4];
	unsigned long tx_rate;
	unsigned long rx_rate;
	unsigned char cap_phymode;
	unsigned char mlo_enable;
	unsigned char mld_mac[6];
	signed char SignalStrength;
	unsigned long ErrorsSent;
	unsigned long ErrorsReceived;
	unsigned long RetryCount;
	struct mtk_mlo_link_information mlo_link[3];
	unsigned char tx_dcm;
	unsigned char rx_dcm;
};

#define MODE_CCK 0
#define MODE_OFDM 1
#define MODE_HTMIX 2
#define MODE_HTGREENFIELD 3
#define MODE_VHT 4
#define MODE_HE 5
#define MODE_EHT 6

#define MODE_HE_SU	8
#define MODE_HE_24G 7
#define MODE_HE_EXT_SU	9
#define MODE_HE_TRIG	10
#define MODE_HE_MU	11
#define MODE_EHT_ER_SU	13
#define MODE_EHT_TB	14
#define MODE_EHT_MU	15
#define MODE_UNKNOWN 255

#define MODE_HE_SU_REMAPPING  5
#define MODE_HE_EXTSU_REMAPPING  6

#define IS_HE_MODE(mode)\
	((mode >= MODE_HE) && (mode <= MODE_HE_MU))

/* BW */
enum oid_bw {
	BAND_WIDTH_20,
	BAND_WIDTH_40,
	BAND_WIDTH_80,
	BAND_WIDTH_160,
	BAND_WIDTH_10,
	BAND_WIDTH_5,
	BAND_WIDTH_8080,
	BAND_WIDTH_320,
	BAND_WIDTH_BOTH,
	BAND_WIDTH_25,
	BAND_WIDTH_20_242TONE,
	BAND_WIDTH_NUM
};

/* BW */
#define BW_20		BAND_WIDTH_20
#define BW_40		BAND_WIDTH_40
#define BW_80		BAND_WIDTH_80
#define BW_160		BAND_WIDTH_160
#define BW_10		BAND_WIDTH_10
#define BW_5		BAND_WIDTH_5
#define BW_8080		BAND_WIDTH_8080
#define BW_25		BAND_WIDTH_25
#define BW_20_242TONE	BAND_WIDTH_20_242TONE
#define BW_320		BAND_WIDTH_320
#define BW_NUM		BAND_WIDTH_NUM

#endif
