#!/bin/sh /etc/rc.common
START=99

printMsg() {
    local msg="$1"
    logger -t "${PROGRAM}" "${msg}"
} 

restart(){                                                                                                       
  /usr/bin/fancts.sh &
  printMsg "Airpi风扇控制模块开始工作！"
  cp /usr/bin/footer.htm /usr/share/ucode/luci/template/themes/argon/footer.ut
  cp /usr/bin/wps /etc/rc.button/wps
}

start(){
  /usr/bin/fancts.sh &
  printMsg "Airpi风扇控制模块开始工作！"
  cp /usr/bin/footer.htm /usr/share/ucode/luci/template/themes/argon/footer.ut
  cp /usr/bin/wps /etc/rc.button/wps
}
